# 사이트 기본 설정
title: "GRIT그릿과학쟁이 & 일산SP과학"
description: "새로운 과학 학습 밀착 관리 시스템 - 심화학습연구소"
url: "https://shellem40-pixel.github.io"
baseurl: "/gritscience"

# 테마 설정
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" 

# 작성자 설정
author:
  name: "과학쟁이 원장"
  bio: "학부모의 절실한 마음으로 한 명 한 명 정성껏 가르치겠습니다."
  location: "일산후곡, 김포, 운정"
  email: "shellem40@gmail.com"

# 플러그인 (에러 해결을 위한 캐시 플러그인 포함)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# 테마 설정
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "my_custom_skin" # <--- "default" 였던 것을 방금 만든 파일 이름으로 변경합니다.

# 기본 레이아웃 및 경로 설정
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single

# Search (검색 기능 설정)
search: true
search_full_content: true # 본문 내용까지 모두 검색할지 여부
search_provider: lunr # 기본 검색 엔진 사용