# 사이트 기본 설정
title: "GRIT그릿과학쟁이 & 일산SP과학"
description: "새로운 과학 학습 밀착 관리 시스템 - 심화학습연구소"
url: "https://shellem40-pixel.github.io"
baseurl: "/gritscience"

# 테마 설정 (Minimal Mistakes 원격 테마 적용)
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" 

# 작성자 설정
author:
  name: "과학쟁이 원장"
  bio: "학부모의 절실한 마음으로 한 명 한 명 정성껏 가르치겠습니다."
  location: "일산후곡, 김포, 운정"
  email: "shellem40@gmail.com"

# 플러그인
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# 기본 레이아웃 설정
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single
<<<<<<< HEAD
<<<<<<< HEAD
      author_profile: true
=======
      author_profile: true
>>>>>>> fc08213acad7ca19cd860a361a11fc1ae7dc5354
=======
>>>>>>> d37e88355107d140b274aa612a96bd88006daa62
